"""HISTORA flagship case study — a research session, end to end, as a scientist would live it.

This is the composition Fable's review pointed to: not new science, not new engineering — the whole machine
(staging -> shared-proxy engine -> three axes -> genetics -> proteins/3-D -> uncertainty) assembled into ONE
falsifiable *research line* around a single, honest anchor.

THE ANCHOR (deliberately safe): **periodontal therapy** is the intervention lever — non-pharmacological,
and the exact edge the engine is calibrated on (ΔhsCRP after scaling-and-root-planing). The **IL-6R node**
is the causal anchor: two-sample cis-MR supports IL-6R -> coronary disease as causal while *circulating CRP*
-> CAD is null (the marker isn't causal; the node is), and **tocilizumab** (an IL-6Rα-blocking antibody) is
cited only as pharmacological *proof that the node is druggable and causal* — NEVER as a proposed treatment.
The research line HISTORA generates: does lowering the periodontal IL-6 source, acting on that same causal
node non-pharmacologically, move the predicted systemic markers in the direction the genetics implies?

HONESTY RED-LINES (enforced in the text, not bolted on):
  * hypothesis-generation, never efficacy; non-diagnostic; population/parameter-level; no patient value.
  * a named drug is a mechanistic/causal-node anchor only, never a prescribing suggestion.
  * MR supports a causal DIRECTION of a node — it is not evidence any intervention works in patients;
    calibration != validation; effect sizes are modest and periodontitis is one contributor among many.
  * the nulls stay loud (circulating-CRP-null vs IL-6R-node-causal; the Alzheimer's axis stays exploratory).
  * every prediction ships its refutation and names its shakiest assumption.

Offline and reproducible (numbers come from the pinned engine, never regenerated by a model). Usage:
    python demo/run_case_study.py            # → case_study.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
sys.path.insert(0, os.path.dirname(__file__))

from histora.proteins import signaling_axis                       # the IL-6 -> IL-6Rα/gp130 -> CRP node
from run_demo import build_brief, _rule                           # reuse the REAL engine composition


def research_line(brief: dict) -> dict:
    """Assemble the falsifiable intervention hypothesis from the engine's own numbers — no new science."""
    cf = brief["engine"]["counterfactuals"]
    crp = brief["engine"]["ranges_over_uncertainty"]["crp_mg_l"]
    axis = signaling_axis()
    toci = axis["therapeutic"]
    return {
        "title": "Research line — periodontal therapy on the IL-6R node (falsifiable, non-diagnostic)",
        "lever": {
            "intervention": "periodontal therapy (scaling & root planing) — NON-PHARMACOLOGICAL",
            "why_this_lever": "it removes the chronic oral IL-6 source; it is the exact edge the engine is "
                              "calibrated on (ΔhsCRP after therapy), so its predicted effect is anchored, not asserted.",
            "predicted_delta_crp_mg_l": cf["periodontal_therapy"]["delta_crp_mg_l"],
            "predicted_crp_range_mg_l": [crp["lo"], crp["hi"]],
        },
        "causal_node": {
            "node": "IL-6R (IL-6Rα, UniProt P08887) → gp130 (IL6ST) → hepatic CRP",
            "genetic_support": "cis-MR: IL-6R → coronary disease CAUSAL (LD-aware β≈+0.705); "
                               "circulating CRP → CAD NULL — the marker is not causal, the node is.",
            "pharmacological_proof_of_node": (
                f"{toci['agent']} ({toci['action']}, DrugBank {toci['drugbank']}) shows the node is "
                "druggable and causal — cited as mechanistic proof ONLY, never as a proposed treatment."),
            "the_hypothesis": "if the IL-6R node mediates the systemic effect, then lowering the periodontal "
                              "IL-6 source (the non-pharmacological lever) should move the predicted markers "
                              "in the SAME direction the genetics implies — a testable research line, not a therapy.",
        },
        "what_would_refute_it": [
            "If periodontal therapy did not lower systemic hs-CRP within the predicted range, the ε "
            "calibration (and this whole lever) is wrong.",
            "If an IL-6R-instrumented analysis showed no coronary effect, the causal-node premise fails.",
            "If the systemic marker moved OPPOSITE to the genetic direction, the mediation hypothesis is refuted.",
        ],
        "shakiest_assumption": "that the population-level IL-6R causal direction transfers to the "
                               "periodontal-source lever in an individual stratum — untested; this is the "
                               "hypothesis a lab would design a study to probe, not a conclusion.",
        "honest_scope": "Hypothesis-generation for a research program — NOT a treatment, prevention, or "
                        "diagnosis. Effect sizes are modest; periodontitis is one contributor among many. "
                        "MR ≠ RCT; calibration ≠ validation. The Alzheimer's axis stays EXPLORATORY.",
        "non_diagnostic": True,
    }


def print_case_study(brief: dict, line: dict) -> None:
    print(_rule("HISTORA — flagship case study: a research session (non-diagnostic, hypothesis-generation)"))
    print("A scientist's end-to-end session: one structural case → one shared proxy → three axes → genetics")
    print("→ proteins/3-D → a single falsifiable research line. Every number from the pinned engine.")

    print(_rule("① The case (structural bands only) + the missing-data flag"))
    print(f"  {brief['structural_stratum']}")
    for f in brief["missing_data_flags"]:
        print(f"  MISSING → collection flag (never imputed): {f['field']} [{f['impact']}] — {f['why']}")

    print(_rule("② Claude's oral-systemic hypotheses (each citing its input fields)"))
    for a in brief["relational_hypotheses"]:
        if isinstance(a, dict) and "axis" in a:
            print(f"  • [{a['axis']}] {a['hypothesis']}  ↳ {', '.join(a.get('from', []))}")

    print(_rule("③ Engine — the shared proxy forks to three axes (ranges, not points)"))
    env = brief["engine"]["ranges_over_uncertainty"]
    print(f"  CRP (mg/L)       median {env['crp_mg_l']['median']}  90% [{env['crp_mg_l']['lo']}, {env['crp_mg_l']['hi']}]")
    print(f"  HbA1c shift (pp) median {env['hba1c_shift_pp']['median']}  90% [{env['hba1c_shift_pp']['lo']}, {env['hba1c_shift_pp']['hi']}]")
    print(f"  tau-α rel incr   median {env['tau_alpha_rel_increase']['median']}  90% [{env['tau_alpha_rel_increase']['lo']}, {env['tau_alpha_rel_increase']['hi']}]  (EXPLORATORY)")

    print(_rule("④ Genetics + proteins — where the causal node lives"))
    for name, verdict in brief["validation"]["mendelian_randomization"]:
        print(f"  MR   {name:28s} {verdict}")
    ax = signaling_axis()
    chain = " → ".join(n["mediator"] for n in ax["nodes"])
    print(f"  node  {chain}   (UniProt/PDB connector resolves the real 3-D structures in Claude Science)")
    print(f"  drug  {ax['therapeutic']['agent']} — IL-6Rα blockade: proof the node is causal/druggable (NOT a treatment)")

    print(_rule("⑤ The research line HISTORA generates (falsifiable, honest)"))
    print(f"  LEVER: {line['lever']['intervention']}")
    print(f"    predicted ΔhsCRP after therapy: {line['lever']['predicted_delta_crp_mg_l']} mg/L "
          f"(CRP 90% range [{line['lever']['predicted_crp_range_mg_l'][0]}, {line['lever']['predicted_crp_range_mg_l'][1]}])")
    print(f"  NODE: {line['causal_node']['node']}")
    print(f"    {line['causal_node']['genetic_support']}")
    print(f"  HYPOTHESIS: {line['causal_node']['the_hypothesis']}")
    print("  ⟂ would refute it:")
    for r in line["what_would_refute_it"]:
        print(f"      - {r}")
    print(f"  shakiest assumption: {line['shakiest_assumption']}")
    print(f"\n  {line['honest_scope']}")
    print(f"  {brief['guardrail']}")


def main() -> None:
    ap = argparse.ArgumentParser(description="HISTORA flagship case study — one falsifiable research line")
    ap.add_argument("--case", default=os.path.join(os.path.dirname(__file__), "case.json"))
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "case_study.json"))
    args = ap.parse_args()

    with open(args.case) as f:
        record = json.load(f)
    brief = build_brief(record, live=False)
    line = research_line(brief)
    report = {"brief": brief, "research_line": line}

    print_case_study(brief, line)
    with open(args.out, "w") as f:
        json.dump(report, f, indent=2)
    print("\nwrote:", args.out)


if __name__ == "__main__":
    main()
